name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Trigger Render deploy
      run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RJServiceID }}/deploys \
            -H "Authorization: Bearer ${{ secrets.RJApiKey }}" \
            -H "Content-Type: application/json"
